addGCPs:
  enabled: true
  gcp_crs: EPSG::32633
  marker_location_accuracy: 0.1
  marker_projection_accuracy: 8
  optimize_w_gcps_only: true
alignPhotos:
  adaptive_fitting: true
  downscale: 0
  enabled: true
  mask_tiepoints: true
buildDenseCloud:
  cell_size: 50.0
  classes: ALL
  classify: true
  downscale: 1
  enabled: true
  export: false
  filter_mode: Metashape.MildFiltering
  format: Metashape.PointsFormatLAS
  keep_depth: true
  max_angle: 15.0
  max_distance: 1.0
  max_neighbors: 100
  point_confidence: true
  point_confidence_max: 10
  reuse_depth: false
buildMesh:
  enabled: true
  face_count: Metashape.CustomFaceCount
  face_count_custom: 200000
  source_data: Metashape.DenseCloudData
  surface_type: Metashape.Arbitrary
  vertex_confidence: true
  volumetric_masks: false
buildTexture:
  blending_mode: Metashape.MosaicBlending
  enabled: true
  mapping_mode: Metashape.GenericMapping
  texture_size: 8192
calibrateReflectance:
  enabled: false
  panel_filename: RP04-1923118-OB.csv
  use_reflectance_panels: true
  use_sun_sensor: true
detectGCPs:
  aruco_dict: aruco.DICT_6X6_250
  corner: topright
  enabled: true
  template:
    enabled: true
    template_file_path: ../markers/markers_circle.png
    template_size: 0.2
extractObject:
  enabled: false
  extraction_method: None
load_project: ''
masks:
  enabled: true
  mask_path: \\gis\Processing\Anna\EK05\100MEDIA
  mask_source: Metashape.MaskSourceFile
multispectral: false
networkProcessing:
  enabled: true
  server_ip: gis
optimizeCameras:
  adaptive_fitting: true
  enabled: true
output_path: \\gis\Processing\Anna\EK05\metashape
photo_path: \\gis\Processing\Anna\EK05
project_crs: EPSG::32633
project_path: \\gis\Processing\Anna\EK05\metashape
run_name: EK05
subdivide_task: true