# This is an example yaml configuration for the photo background removal script
# It is fully compatible with the UC Davis and UNIS Metashape yml formatting.

# The path to the directory of photos
# If there are multiple photo folders, set path to the folder that contains all the photo folders
photo_path: 'C:\Users\Peter\OneDrive\Bilder\test'

detectGCPs:
    enabled: True 
    aruco_dict: aruco.DICT_6X6_250 # options include: aruco.DICT_6X6_250, aruco.DICT_4X4_50
    corner: "centre" # options: bottomleft (=1), topleft (2), topright (3), bottomright (4), centre (0).
    template:
        enabled: True # Keep false when using geopackage with long/lat data
        template_file_path: "../markers/markers_circle.png"
        template_size: 0.20 # one-sided dimension of a mxm square in metres. The example in Markers is a 20x20 cm frame, i.e. 0.20 m here.

